#!/bin/bash

SERVER=( 'YOUR REMOTE SERVER' )
DEPLOY_PATH=/var/www/freeweibo
USER=username

ENVIRONMENT=${1:-"production"}
REF=${2:-"master"}

trap 'test -n "$SUCCESS" || echo "  error: aborted"' EXIT
echo "* Deploying $ENVIRONMENT/$REF"

ssh $USER@$SERVER "cd $DEPLOY_PATH && \
                   git reset --hard && \
                   git checkout $REF && \
                   git pull origin master&& \
                   npm install && 
                   stylus  public/stylesheets/ &&\
                   /etc/init.d/filterback restart"

SUCCESS=true
